name: Server CI Azure

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    # install dependencies, build, and test
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

   - uses: azure/appservice-actions/webapp@master
     with:
       app-name: tech-trainer-server
       publish-profile: ${{ secrets.techTrainerServerPublishSettings }}
       package: '.'
