name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and deploy to azure
      run: |
        npm install
        npm run build --if-presen
      env:
        CI: true
      # Deploy to App Service
      - uses: azure/appservice-actions/webapp@master
      - name: tech-trainer-server
        with:
          app-name: tech-trainer-server
          package: '.'
          publish-profile: ${{ secrets.techTrainerServerPublishSettings }}
