name: Server CI Azure

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - uses: actions/checkout@master

      # install dependencies, build, and test
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # deploy web app using publish profile credentials
      - uses: azure/appservice-actions/webapp@master
        with:
          app-name: node-rn
          publish-profile: ${{ secrets.techTrainerServerPublishSettings }}
